### ISSUE TITLE
Error:If set params in chinese

### ISSUE THREAD

**Issue by BetaMatrix** [tapnair/ParamEdit#1]
Command created failed: Traceback (most recent call last):
  File "C:/Users/XXXX/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/ParamEdit\ParamEditCommand.py", line 54, in on_create
    param.expression)
  File "C:/Users/XXXX/AppData/Local/Autodesk/webdeploy/production/8556a3e1d81f6c5f0bca3f1440fbfa311d80a809/Api/Python/packages\adsk\core.py", line 4551, in addStringValueInput
    return _core.CommandInputs_addStringValueInput(self, *args)
RuntimeError: 3 : invalid argument id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/XXXX/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/ParamEdit\Fusion360Utilities\Fusion360CommandBase.py", line 396, in notify
    self.cmd_object_.on_create(command_, inputs_)
SystemError: <built-in function delete_UserParameters> returned a result with an error set

**Comment by PietroPizzi69** [comment]
I have the same problem with european umlauts (äöü...).

**Comment by PietroPizzi69** [comment]
... and ß (scharfes s)
